# Worker builder
FROM golang:1.21-alpine as worker_builder

WORKDIR /app

COPY go.* ./

RUN go mod download

COPY ./cmd ./cmd
COPY ./internal ./internal
COPY ./ent ./ent
COPY ./pkg ./pkg

RUN go build -v -o ./bin/worker ./cmd/worker/worker.go

# Runtime
FROM python:3.10-slim

WORKDIR /

COPY --from=worker_builder /app/bin/worker .

COPY ./data ./data

COPY ./.env* .

RUN pip3 install rembg[cli]==2.0.50

# RUN python -c 'from rembg.bg import download_models; download_models()'

CMD ["/worker"]
