databases:
  - name: srv.postgres
    plan: free
    user: bgeraser
    databaseName: bgeraser
    postgresMajorVersion: 15
    ipAllowList: []

services:
  - type: redis
    name: srv.redis.queues
    plan: sfree
    maxmemoryPolicy: noeviction
    ipAllowList: []

  # API
  - type: web
    name: web.api
    runtime: docker
    plan: free
    healthCheckPath: /ping
    envVars:
      - fromGroup: env-settings
    dockerfilePath: ./Dockerfile

envVarGroups:
  # Environment
  - name: env-settings
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: bgeraser
      - key: DB_NAME
        value: bgeraser
      - key: SERVER_PORT
        value: 8080
      - key: ENABLE_SONIC_JSON
        value: 1
      - key: ENABLE_PREFORK
        value: 0
      - key: ENABLE_PROFILING
        value: 0
      - key: CPU_PROFILE
        value: ./prof/cpu.prof
      - key: MEM_PROFILE
        value: ./prof/mem.prof
      - key: STORAGE_LOCAL_PATH
        value: data/images
      - key: STORAGE_BUCKET
        sync: false
      - key: STORAGE_BUCKET_URL
        sync: false
      - key: AWS_REGION
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: QUEUES_HOST
        sync: false
      - key: QUEUES_PORT
        sync: false
