// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ImagesColumns holds the columns for the "images" table.
	ImagesColumns = []*schema.Column{
		{Name: "oid", Type: field.TypeUUID},
		{Name: "format", Type: field.TypeString},
		{Name: "size", Type: field.TypeInt64},
		{Name: "original_filename", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// ImagesTable holds the schema information for the "images" table.
	ImagesTable = &schema.Table{
		Name:       "images",
		Columns:    ImagesColumns,
		PrimaryKey: []*schema.Column{ImagesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "image_oid",
				Unique:  false,
				Columns: []*schema.Column{ImagesColumns[0]},
			},
		},
	}
	// ImageProcessesColumns holds the columns for the "image_processes" table.
	ImageProcessesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "kind", Type: field.TypeString},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
		{Name: "errored_at", Type: field.TypeTime, Nullable: true},
		{Name: "error_reason", Type: field.TypeString, Nullable: true},
		{Name: "image_id", Type: field.TypeUUID},
		{Name: "result_id", Type: field.TypeUUID, Nullable: true},
	}
	// ImageProcessesTable holds the schema information for the "image_processes" table.
	ImageProcessesTable = &schema.Table{
		Name:       "image_processes",
		Columns:    ImageProcessesColumns,
		PrimaryKey: []*schema.Column{ImageProcessesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "image_processes_images_origin",
				Columns:    []*schema.Column{ImageProcessesColumns[5]},
				RefColumns: []*schema.Column{ImagesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "image_processes_images_result",
				Columns:    []*schema.Column{ImageProcessesColumns[6]},
				RefColumns: []*schema.Column{ImagesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "imageprocess_id",
				Unique:  true,
				Columns: []*schema.Column{ImageProcessesColumns[0]},
			},
			{
				Name:    "imageprocess_image_id_image_id",
				Unique:  true,
				Columns: []*schema.Column{ImageProcessesColumns[5], ImageProcessesColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ImagesTable,
		ImageProcessesTable,
	}
)

func init() {
	ImageProcessesTable.ForeignKeys[0].RefTable = ImagesTable
	ImageProcessesTable.ForeignKeys[1].RefTable = ImagesTable
}
