// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/leorcvargas/bgeraser/ent/image"
	"github.com/leorcvargas/bgeraser/ent/imageprocess"
	"github.com/leorcvargas/bgeraser/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	imageFields := schema.Image{}.Fields()
	_ = imageFields
	// imageDescFormat is the schema descriptor for format field.
	imageDescFormat := imageFields[1].Descriptor()
	// image.FormatValidator is a validator for the "format" field. It is called by the builders before save.
	image.FormatValidator = imageDescFormat.Validators[0].(func(string) error)
	// imageDescSize is the schema descriptor for size field.
	imageDescSize := imageFields[2].Descriptor()
	// image.SizeValidator is a validator for the "size" field. It is called by the builders before save.
	image.SizeValidator = imageDescSize.Validators[0].(func(int64) error)
	// imageDescOriginalFilename is the schema descriptor for original_filename field.
	imageDescOriginalFilename := imageFields[3].Descriptor()
	// image.OriginalFilenameValidator is a validator for the "original_filename" field. It is called by the builders before save.
	image.OriginalFilenameValidator = imageDescOriginalFilename.Validators[0].(func(string) error)
	// imageDescCreatedAt is the schema descriptor for created_at field.
	imageDescCreatedAt := imageFields[4].Descriptor()
	// image.DefaultCreatedAt holds the default value on creation for the created_at field.
	image.DefaultCreatedAt = imageDescCreatedAt.Default.(func() time.Time)
	// imageDescUpdatedAt is the schema descriptor for updated_at field.
	imageDescUpdatedAt := imageFields[5].Descriptor()
	// image.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	image.DefaultUpdatedAt = imageDescUpdatedAt.Default.(func() time.Time)
	// image.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	image.UpdateDefaultUpdatedAt = imageDescUpdatedAt.UpdateDefault.(func() time.Time)
	// imageDescID is the schema descriptor for id field.
	imageDescID := imageFields[0].Descriptor()
	// image.DefaultID holds the default value on creation for the id field.
	image.DefaultID = imageDescID.Default.(func() uuid.UUID)
	imageprocessFields := schema.ImageProcess{}.Fields()
	_ = imageprocessFields
	// imageprocessDescKind is the schema descriptor for kind field.
	imageprocessDescKind := imageprocessFields[3].Descriptor()
	// imageprocess.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	imageprocess.KindValidator = imageprocessDescKind.Validators[0].(func(string) error)
	// imageprocessDescID is the schema descriptor for id field.
	imageprocessDescID := imageprocessFields[0].Descriptor()
	// imageprocess.DefaultID holds the default value on creation for the id field.
	imageprocess.DefaultID = imageprocessDescID.Default.(func() uuid.UUID)
}
