// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Image is the predicate function for image builders.
type Image func(*sql.Selector)

// ImageProcess is the predicate function for imageprocess builders.
type ImageProcess func(*sql.Selector)
